-- Expand Product
ALTER TABLE "Product" ADD COLUMN "costPrice" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN "salePrice" DOUBLE PRECISION;
ALTER TABLE "Product" ADD COLUMN "minStock" INTEGER NOT NULL DEFAULT 0;

-- Expand SaleItem
ALTER TABLE "SaleItem" ADD COLUMN "unitPrice" DOUBLE PRECISION;
ALTER TABLE "SaleItem" ADD COLUMN "unitCost" DOUBLE PRECISION;